### ISSUE TITLE
Incompatible scalaz-stream dependency in 0.7.0

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#270]
After upgrading to 0.7.0, I have warnings from SBT saying that there is a dependency on scalaz-stream 0.6a, which is being evicted by another dependency on 0.7a.

The problem is apparently caused by the chain of http4s-argonaut (0.7.0) -> http4s-jawn (0.7.0) -> jawn-streamz (0.3.1). jawn-streamz hasn't been updated in maven central since Dec 2014.

The project seems to build and run fine, but the warning appears during every compile, so I'd like to clean it up. Am I doing something wrong, or does the dependency need to be fixed in http4s?

build.sbt:
```scala
val http4sVersion     = "0.7.0"

libraryDependencies ++= Seq(
  "org.http4s"        %% "http4s-dsl"                % http4sVersion     % "compile, test",
  "org.http4s"        %% "http4s-argonaut"           % http4sVersion     % "compile, test",
  "org.http4s"        %% "http4s-jetty"              % http4sVersion     % "compile, test",
```

console:
```
> compile
[info] Updating {file:/Users/moss/slamdata/ws4/}web...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.scalaz.stream:scalaz-stream_2.11:0.6a -> 0.7a
[warn] Run 'evicted' to see detailed eviction warnings
...
> evicted
[info] Updating {file:/Users/moss/slamdata/ws4/}core...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/Users/moss/slamdata/ws4/}web...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.scalaz.stream:scalaz-stream_2.11:0.6a -> 0.7a (caller: web:web_2.11:2.0.0-SNAPSHOT, org.http4s:jawn-streamz_2.11:0.3.1, core:core_2.11:2.0.0-SNAPSHOT, org.http4s:http4s-core_2.11:0.7.0)
[warn] 	* org.eclipse.jetty:jetty-server:9.2.2.v20140723 -> 9.2.10.v20150310 (caller: org.eclipse.jetty:jetty-security:9.2.10.v20150310, io.dropwizard.metrics:metrics-jetty9:3.1.1)
[warn] 	* org.eclipse.jetty:jetty-io:9.2.2.v20140723 -> 9.2.10.v20150310 (caller: org.eclipse.jetty:jetty-server:9.2.2.v20140723, org.eclipse.jetty:jetty-server:9.2.10.v20150310)
[warn] 	* org.eclipse.jetty:jetty-http:9.2.2.v20140723 -> 9.2.10.v20150310 (caller: org.eclipse.jetty:jetty-server:9.2.2.v20140723, org.eclipse.jetty:jetty-server:9.2.10.v20150310)
[warn] 	* org.eclipse.jetty:jetty-util:9.2.2.v20140723 -> 9.2.10.v20150310 (caller: org.eclipse.jetty:jetty-io:9.2.2.v20140723, org.eclipse.jetty:jetty-io:9.2.10.v20150310, org.eclipse.jetty:jetty-http:9.2.2.v20140723, org.eclipse.jetty:jetty-http:9.2.10.v20150310)
[warn] 	* com.chuusai:shapeless_2.11:2.0.0 -> 2.1.0 (caller: org.parboiled:parboiled_2.11:2.1.0, com.github.julien-truffaut:monocle-generic_2.11:1.1.1)
[warn] 	* org.scalacheck:scalacheck_2.11:1.11.4 -> 1.12.2 (caller: org.scalaz:scalaz-scalacheck-binding_2.11:7.1.2, com.github.julien-truffaut:monocle-law_2.11:1.1.1)
[success] Total time: 1 s, completed May 13, 2015 10:28:16 AM
> what-depends-on org.scalaz.stream scalaz-stream_2.11 0.6a
[info] org.scalaz.stream:scalaz-stream_2.11:0.6a (evicted by: 0.7a)
[info]   +-org.http4s:jawn-streamz_2.11:0.3.1
[info]     +-org.http4s:http4s-jawn_2.11:0.7.0
[info]       +-org.http4s:http4s-argonaut_2.11:0.7.0
[info]         +-web:web_2.11:2.0.0-SNAPSHOT
...
> what-depends-on org.scalaz.stream scalaz-stream_2.11 0.7a
[info] org.scalaz.stream:scalaz-stream_2.11:0.7a
...
[info]   +-org.http4s:http4s-core_2.11:0.7.0
[info]   | +-org.http4s:http4s-argonaut_2.11:0.7.0
[info]   | | +-web:web_2.11:2.0.0-SNAPSHOT
```

**Comment by bryce-anderson** [comment]
@mossprescott, I think you're right; ```jawn-streamz``` appears to not have been updated before the release. @rossabaker, do you have time to do a release of that? I don't know much about the details of it.

**Comment by rossabaker** [comment]
I just released jawn-streamz-0.4.1.  I'll get it merged here after it syncs to Maven Central.

**Comment by bryce-anderson** [comment]
I believe this is closed by f73d37e. Please reopen if problem persists.

**Comment by mossprescott** [comment]
Looks like I'm having a similar issue with 0.8.2-SNAPSHOT. Now the versions of scalaz-stream are 0.7a (required by jawn-streamz 0.4.1) and 0.7.1a (required by http4s-core). Again, this is based on what I get from `what-depends-on`.

**Comment by rossabaker** [comment]
I thought those were binary compatible and 0.7.1a would win, but let's cut a new release of jawn-streamz to remove all confusion.
