### ISSUE TITLE
[Bug] Accept header not appended properly in 0.23.0-RC1

### ISSUE THREAD

**Issue by Qi77Qi** [http4s/http4s#4987]
I tried the following ways to construct the `Accept` header

```
    Headers(
      Accept(
        MediaRangeAndQValue
          .withDefaultQValue(MediaRange.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get)
      ),
      Header.Raw(ci"Accept", "application/vnd.docker.distribution.manifest.v2+json"),
      Accept.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get
    )
```

But none of them actually appended the header properly.

In previous version, headers in a call looked like this
```
{"@timestamp":"2021-07-28T15:59:16.160Z","@version":"1","message":"HTTP/1.1 GET https://registry-1.docker.io/v2/rtitle/anvil-rstudio-base/blobs/sha256:aaf072362a3bfa231f444af7a05aa24dd83f6d94ba56b3d6d0b365748deac30a Headers(Accept: application/vnd.docker.distribution.manifest.v2+json, Authorization: <REDACTED>, Accept: application/json)","logger_name":"org.http4s.client.middleware.RequestLogger","thread_name":"scala-execution-context-global-1942","severity":"INFO","level_value":20000}
```

But it now looks like this with 0.23.0-RC1
```
{"@timestamp":"2021-07-28T16:07:41.141Z","@version":"1","message":"HTTP/1.1 GET https://registry-1.docker.io/v2/rtitle/anvil-rstudio-base/manifests/0.0.1 Headers(Content-Type: application/vnd.docker.distribution.manifest.v2+json, Authorization: <REDACTED>, Accept: application/json)","logger_name":"org.http4s.client.middleware.RequestLogger","thread_name":"io-compute-8","severity":"INFO","level_value":20000}
```

**Comment by rossabaker** [comment]
This probably goes back to 0.22, which is when the new header model was introduced.  Creating a request this way is fine:

```scala
scala> val req = Request[IO](headers = Headers(
      Accept(
        MediaRangeAndQValue
          .withDefaultQValue(MediaRange.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get)
      ),
      Header.Raw(ci"Accept", "application/vnd.docker.distribution.manifest.v2+json"),
      Accept.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get
    ))
val req = Request[IO](headers = Headers(
     |       Accept(
     |         MediaRangeAndQValue
     |           .withDefaultQValue(MediaRange.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get)
     |       ),
     |       Header.Raw(ci"Accept", "application/vnd.docker.distribution.manifest.v2+json"),
     |       Accept.parse("application/vnd.docker.distribution.manifest.v2+json").toOption.get
     |     ))
req: org.http4s.Request[cats.effect.IO] = Request(method=GET, uri=/, headers=Headers(Accept: application/vnd.docker.distribution.manifest.v2+json, Accept: application/vnd.docker.distribution.manifest.v2+json, Accept: application/vnd.docker.distribution.manifest.v2+json))
```

You're probably calling `expect`, or something related.  That calls `putHeaders` with the media types from the `EntityEncoder`, replacing any existing `Accept` headers.  The former definition of `putHeaders` knew which header keys were singletons (like `Content-Type`) and which were recurring (like `Accept`), and could merge the recurring ones.  That knowledge is lost in the type class model.

I think we could restore the old behavior by appending that Accept header from the encoder instead of putting them.

**Comment by Qi77Qi** [comment]
@rossabaker  thanks for taking a look! yea, I'm using `expectOptionOr`...is there another function that I can use that won't have this behavior?

**Comment by rossabaker** [comment]
All of the client methods that take an `EntityDecoder` do something like this.  As a quick fix, if you put this function on a client syntax trait:

```scala
  implicit class ClientTempSyntax[F[_]](val client: Client[F])(implicit F: MonadCancelThrow[F]) {
    def expectOptionOrHack[A](req: Request[F])(onError: Response[F] => F[Throwable])(implicit
        d: EntityDecoder[F, A]): F[Option[A]] = {
      val r = if (d.consumes.nonEmpty) {
        val m = d.consumes.toList
        req.transformHeaders(_.add(Accept(MediaRangeAndQValue(m.head), m.tail.map(MediaRangeAndQValue(_)): _*)))
      } else req

      client.run(r).use {
        case Successful(resp) =>
          d.decode(resp, strict = false).leftWiden[Throwable].rethrowT.map(_.some)
        case failedResponse =>
          failedResponse.status match {
            case Status.NotFound => Option.empty[A].pure[F]
            case Status.Gone => Option.empty[A].pure[F]
            case _ => onError(failedResponse).flatMap(F.raiseError)
          }
      }
    }
  }
```

And then just call `expectOptionOrHack` instead of `expectOption`.

I've been working toward the 0.23 release today.  We'll have a proper fix in that, and I'll also release an 0.22.1 patch.  Once that's done, you can revert to the standard method, and all should be well.

**Comment by Qi77Qi** [comment]
@rossabaker sounds great...thanks!

**Comment by rossabaker** [comment]
This should be fixed in 0.23.0 (and 0.22.1).

**Comment by Qi77Qi** [comment]
hey @rossabaker , is this fix in `1.0.0-M24`? it seems with `1.0.0-M24`, I'm still seeing the same behavior

**Comment by Qi77Qi** [comment]
just removed the hack I had previously, and tests all passed....can confirm the fix is in this way too :) ...sry should've done this before asking

**Comment by rossabaker** [comment]
Not at all.  I'm glad to hear that it worked!  I just think it's a neat feature of GitHub and wanted to share. :smile:
